version: '3.1'

services:
  adminer:
    image: adminer
    ports:
      - 7777:8080

  db:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
    ports:
      - 3306:3306
  php-fpm:
    image: webdevops/php-dev:7.4
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - db
  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - 80:80
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm
